/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.9.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as classes from "../classes.js";
import type * as embed from "../embed.js";
import type * as files from "../files.js";
import type * as http from "../http.js";
import type * as myHttpActions from "../myHttpActions.js";
import type * as problemSets from "../problemSets.js";
import type * as problems from "../problems.js";
import type * as studentResponses from "../studentResponses.js";
import type * as students from "../students.js";
import type * as tasks from "../tasks.js";
import type * as twilio from "../twilio.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  classes: typeof classes;
  embed: typeof embed;
  files: typeof files;
  http: typeof http;
  myHttpActions: typeof myHttpActions;
  problemSets: typeof problemSets;
  problems: typeof problems;
  studentResponses: typeof studentResponses;
  students: typeof students;
  tasks: typeof tasks;
  twilio: typeof twilio;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
