/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Wu249cGBkP8
 */
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export function Component1() {
  return (
    <div className="w-full min-h-screen flex flex-col">
      <main className="flex-1">
        <div className="container py-6 px-4 md:py-12 md:px-6">
          <div className="flex items-center gap-4 mb-4">
            <h1 className="text-3xl font-bold tracking-tighter">My Lectures</h1>
            <Button size="sm">New Lecture</Button>
          </div>
          <Card>
            <CardContent className="p-4 md:p-6">
              <div className="flex items-center gap-4">
                <div className="flex-1">
                  <h2 className="text-xl font-semibold">Introduction to Computer Science</h2>
                  <p className="text-sm text-gray-500 dark:text-gray-400">January 28th</p>
                </div>
                <div className="flex flex-col items-end text-right">
                  <div className="text-sm">
                    <strong>Students:</strong>
                    32
                  </div>
                  <div className="space-x-2 mt-2">
                    <Button size="sm">View Slides</Button>
                    <Button size="sm" variant="outline">
                      View Responses
                    </Button>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}
