// /**
//  * This code was generated by v0 by Vercel.
//  * @see https://v0.dev/t/DdTq4OHPevP
//  */
import { LoginButton } from "@/components/ui/loginButton";
import Link from "next/link";
import Wave from "./ui/wave";
import React, { useEffect, useState } from "react";

export function HomeUnauth() {
  const [title, setTitle] = useState("");
  const [showContent, setShowContent] = useState(false);
  const [showCursor, setShowCursor] = useState(true);
  const [showGetStarted, setShowGetStarted] = useState(false); // State to control the visibility of the Get Started button

  useEffect(() => {
    const fullTitle = "Welcome to Ta.ai";
    let currentTitle = "";

    const typingTimer = setInterval(() => {
      if (currentTitle.length < fullTitle.length) {
        currentTitle = fullTitle.substring(0, currentTitle.length + 1);
        setTitle(currentTitle);
      } else {
        clearInterval(typingTimer);
        setShowCursor(false); // Immediately hide the cursor once typing is finished
        // Wait a bit before showing the rest of the content
        setTimeout(() => {
          setShowContent(true);
          setTimeout(() => setShowGetStarted(true), 500); // Delay the appearance of the Get Started button after the content fades in
        }, 500);
      }
    }, 100); // Adjust typing speed as needed

    return () => {
      clearInterval(typingTimer);
    };
  }, []);

  return (
    <>
      <section className="flex items-center justify-center w-full h-screen relative overflow-hidden">
        <div className="absolute top-1/2 left-0 w-full -translate-y-1/2">
          {/* <Wave /> This ensures the Wave component covers the entire section as a background */}
        </div>
        <div className="text-center z-10 relative">
          {" "}
          {/* This container is for your content */}
          <h1 className="text-4xl font-extrabold tracking-tighter sm:text-6xl">
            {title}
            <span
              className={`${showCursor ? "inline" : "hidden"} cursor`}
              style={{ width: "1px" }}
            >
              |
            </span>
          </h1>
          <div className={`${showContent ? "fadeIn" : "opacity-0"}`}>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              No more knowledge gaps for your students
            </p>
            <div
              className={`flex justify-center gap-4 mt-8 ${
                showGetStarted ? "fadeIn" : "opacity-0"
              }`}
            >
              <Link
                className="inline-flex h-12 items-center justify-center rounded-md bg-orange-500 px-10 text-lg font-semibold text-white shadow transition-colors hover:bg-orange-700 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-orange-200 disabled:pointer-events-none disabled:opacity-50 dark:bg-orange-500 dark:hover:bg-orange-600 dark:focus-visible:ring-orange-300"
                href="/api/auth/login"
                onClick={(e) => {
                  e.preventDefault();
                  window.location.href = "/api/auth/login";
                }}
              >
                Get Started
              </Link>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
