/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DdTq4OHPevP
 */
import { Button } from "@/components/ui/button";

export function HomeUnauth() {
  return (
    <div
      key="1"
      className="relative flex flex-col items-center justify-center h-screen w-full min-h-screen bg-black"
    >
      <div className="absolute top-0 left-0 right-0 bottom-0 pointer-events-none z-[-1]">
        <div
          className="absolute w-12 h-12 bg-opacity-20 bg-gray-500 rounded-full"
          style={{
            left: "20%",
            top: "10%",
          }}
        />
        <div
          className="absolute w-12 h-12 bg-opacity-20 bg-gray-500 rounded-full"
          style={{
            left: "70%",
            top: "30%",
          }}
        />
        <div
          className="absolute w-12 h-12 bg-opacity-20 bg-gray-500 rounded-full"
          style={{
            left: "40%",
            top: "50%",
          }}
        />
        <div
          className="absolute w-12 h-12 bg-opacity-20 bg-gray-500 rounded-full"
          style={{
            left: "90%",
            top: "70%",
          }}
        />
        <div
          className="absolute w-12 h-12 bg-opacity-20 bg-gray-500 rounded-full"
          style={{
            left: "10%",
            top: "20%",
          }}
        />
        <div
          className="absolute w-12 h-12 bg-opacity-20 bg-gray-500 rounded-full"
          style={{
            left: "50%",
            top: "80%",
          }}
        />
        <div
          className="absolute w-12 h-12 bg-opacity-20 bg-gray-500 rounded-full"
          style={{
            left: "80%",
            top: "40%",
          }}
        />
        <div
          className="absolute w-12 h-12 bg-opacity-20 bg-gray-500 rounded-full"
          style={{
            left: "30%",
            top: "60%",
          }}
        />
        <div className="absolute w-full h-0.5 bg-gray-500 opacity-20 top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2" />
        <div className="absolute w-0.5 h-full bg-gray-500 opacity-20 top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2" />
        <div className="absolute w-full h-0.5 bg-gray-500 opacity-20 top-1/4 left-1/4 transform -translate-x-1/2 -translate-y-1/2" />
        <div className="absolute w-0.5 h-full bg-gray-500 opacity-20 top-1/4 left-1/4 transform -translate-x-1/2 -translate-y-1/2" />
      </div>
      <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl lg:text-6xl text-white">
        Title
      </h1>
      <h2 className="text-lg text-gray-500">Subtitle</h2>
      {/* <Button
        className="mt-8"
        style={{
          color: "neon-orange",
        }}
      >
        Create Account
      </Button> */}
      <div className="absolute top-4 right-4">
        <Button
          onClick={() => (window.location.href = "/api/auth/login")}
          type="submit"
        >
          Login
        </Button>
      </div>
    </div>
  );
}
