/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TJS9kmioMHT
 */
import { TableCell, TableRow, TableBody, Table } from "@/components/ui/table"
import { Card } from "@/components/ui/card"

export function QuestionBreakdown() {
  return (
    <Card>
      <div>
        <div className="w-full">Question 1</div>
        <div>
          <div className="flex w-full">
            <Table>
              <TableBody className="divide-y">
                <TableRow className="text-sm">
                  <TableCell className="w-3/4">Lorem ipsum dolor sit amet, consectetur</TableCell>
                  <TableCell>%</TableCell>
                </TableRow>
                <TableRow className="text-sm">
                  <TableCell className="w-3/4">adipiscing elit, sed do eiusmod tempor</TableCell>
                  <TableCell>60%</TableCell>
                </TableRow>
                <TableRow className="text-sm">
                  <TableCell className="w-3/4">incididunt ut labore et dolore magna aliqua</TableCell>
                  <TableCell>90%</TableCell>
                </TableRow>
                <TableRow className="text-sm">
                  <TableCell className="w-3/4">Ut enim ad minim veniam, quis nostrud</TableCell>
                  <TableCell>75%</TableCell>
                </TableRow>
                <TableRow className="text-sm">
                  <TableCell className="w-3/4">exercitation ullamco laboris nisi ut</TableCell>
                  <TableCell>85%</TableCell>
                </TableRow>
                <TableRow className="text-sm">
                  <TableCell className="w-3/4">aliquip ex ea commodo consequat</TableCell>
                  <TableCell>70%</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </div>
      </div>
    </Card>
  )
}
