// /**
//  * This code was generated by v0 by Vercel.
//  * @see https://v0.dev/t/uAWBjvTGDVG
//  */
// import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

// export function Student table() {
//   return (
//     <div className="w-full flex items-center justify-center">
//       <div className="text-center mb-4">Number of Students: 5</div>
//       <Table className="w-1/2">
//         <TableHeader>
//           <TableRow>
//             <TableHead className="w-[50px]" />
//             <TableHead className="text-left">Name</TableHead>
//             <TableHead className="text-right">Progress</TableHead>
//           </TableRow>
//         </TableHeader>
//         <TableBody>
//           <TableRow>
//             <TableCell>
//               <img
//                 alt="Avatar"
//                 className="rounded-full"
//                 height="32"
//                 src="/placeholder.svg"
//                 style={{
//                   aspectRatio: "32/32",
//                   objectFit: "cover",
//                 }}
//                 width="32"
//               />
//             </TableCell>
//             <TableCell className="font-medium">Alice</TableCell>
//             <TableCell>
//               <div className="flex items-center space-x-2 text-right">
//                 <span>80%</span>
//               </div>
//               <Progress className="w-1/3">
//                 <div className="h-2" />
//               </Progress>
//             </TableCell>
//           </TableRow>
//           <TableRow>
//             <TableCell>
//               <img
//                 alt="Avatar"
//                 className="rounded-full"
//                 height="32"
//                 src="/placeholder.svg"
//                 style={{
//                   aspectRatio: "32/32",
//                   objectFit: "cover",
//                 }}
//                 width="32"
//               />
//             </TableCell>
//             <TableCell className="font-medium">Bob</TableCell>
//             <TableCell>
//               <div className="flex items-center space-x-2 text-right">
//                 <span>90%</span>
//               </div>
//               <Progress className="w-1/3">
//                 <div className="h-2" />
//               </Progress>
//             </TableCell>
//           </TableRow>
//           <TableRow>
//             <TableCell>
//               <img
//                 alt="Avatar"
//                 className="rounded-full"
//                 height="32"
//                 src="/placeholder.svg"
//                 style={{
//                   aspectRatio: "32/32",
//                   objectFit: "cover",
//                 }}
//                 width="32"
//               />
//             </TableCell>
//             <TableCell className="font-medium">Charlie</TableCell>
//             <TableCell>
//               <div className="flex items-center space-x-2 text-right">
//                 <span>70%</span>
//               </div>
//               <Progress className="w-1/3">
//                 <div className="h-2" />
//               </Progress>
//             </TableCell>
//           </TableRow>
//           <TableRow>
//             <TableCell>
//               <img
//                 alt="Avatar"
//                 className="rounded-full"
//                 height="32"
//                 src="/placeholder.svg"
//                 style={{
//                   aspectRatio: "32/32",
//                   objectFit: "cover",
//                 }}
//                 width="32"
//               />
//             </TableCell>
//             <TableCell className="font-medium">Diana</TableCell>
//             <TableCell>
//               <div className="flex items-center space-x-2 text-right">
//                 <span>60%</span>
//               </div>
//               <Progress className="w-1/3">
//                 <div className="h-2" />
//               </Progress>
//             </TableCell>
//           </TableRow>
//           <TableRow>
//             <TableCell>
//               <img
//                 alt="Avatar"
//                 className="rounded-full"
//                 height="32"
//                 src="/placeholder.svg"
//                 style={{
//                   aspectRatio: "32/32",
//                   objectFit: "cover",
//                 }}
//                 width="32"
//               />
//             </TableCell>
//             <TableCell className="font-medium">Eve</TableCell>
//             <TableCell>
//               <div className="flex items-center space-x-2 text-right">
//                 <span>75%</span>
//               </div>
//               <Progress className="w-1/3">
//                 <div className="h-2" />
//               </Progress>
//             </TableCell>
//           </TableRow>
//         </TableBody>
//       </Table>
//     </div>
//   )
// }
